menu:
  # Home: /
  归档: /archives
  # Reading: /reading
  关于: /about
  主站: http://liam0205.me
  RSS:  /atom.xml

excerpt_link: Read More #摘要链接文字
archive_yearly: false #按年存档
archive_date_format: YYYY [年] MM [月] D [日]

widgets: #配置页脚显示哪些小挂件
  - category
#  - tag
  - tagcloud
  - recent_posts
#  - blogroll

fancybox: true
duoshuo_shortname: cnliam

google_analytics: 44836433
favicon: /favicon.ico
